// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Whoop.HardwareTelemetry.Platform.u202315165.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;

#nullable disable

namespace Whoop.HardwareTelemetry.Platform.u202315165.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260717194519_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Whoop.HardwareTelemetry.Platform.u202315165.Hardware.Domain.Model.Aggregates.Device", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastSyncDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_sync_date");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("model");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("serial_number");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_devices_serial_number");

                    b.ToTable("devices");
                });

            modelBuilder.Entity("Whoop.HardwareTelemetry.Platform.u202315165.Hardware.Domain.Model.Entities.ProcessedTelemetryRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("RecordId")
                        .HasColumnType("bigint")
                        .HasColumnName("record_id");

                    b.HasKey("Id")
                        .HasName("pk_processed_telemetry_records");

                    b.HasIndex("RecordId")
                        .IsUnique()
                        .HasDatabaseName("ix_processed_telemetry_records_record_id");

                    b.ToTable("processed_telemetry_records");
                });

            modelBuilder.Entity("Whoop.HardwareTelemetry.Platform.u202315165.Telemetry.Domain.Model.Aggregates.TelemetryDataRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("recorded_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_telemetry_data_records");

                    b.ToTable("telemetry_data_records");
                });

            modelBuilder.Entity("Whoop.HardwareTelemetry.Platform.u202315165.Telemetry.Domain.Model.Aggregates.TelemetryDataRecord", b =>
                {
                    b.OwnsOne("Whoop.HardwareTelemetry.Platform.u202315165.Telemetry.Domain.Model.ValueObjects.DeviceHealthData", "DeviceHealthData", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<int>("BatteryLevel")
                                .HasColumnType("int")
                                .HasColumnName("battery_level");

                            b1.Property<string>("DeviceStatus")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("varchar(40)")
                                .HasColumnName("device_status");

                            b1.HasKey("Id");

                            b1.ToTable("telemetry_data_records");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsOne("Whoop.HardwareTelemetry.Platform.u202315165.Telemetry.Domain.Model.ValueObjects.VitalSignData", "VitalSignData", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<int>("HeartRate")
                                .HasColumnType("int")
                                .HasColumnName("heart_rate");

                            b1.Property<int>("RespiratoryRate")
                                .HasColumnType("int")
                                .HasColumnName("respiratory_rate");

                            b1.HasKey("Id");

                            b1.ToTable("telemetry_data_records");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.Navigation("DeviceHealthData")
                        .IsRequired();

                    b.Navigation("VitalSignData")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
